version: "3"

services:

  proxy:
    image: dockerflow/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - fimplus
    environment:
      # - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.env == manager]

  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener
    networks:
      - fimplus
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 2

networks:
  fimplus:
    external: true
