version: '3'
services:
  app:
    build: .
    image: hd1-movies

  unit:
    image: hub.fimplus.io/repo/init-hd1-movies:v1.1
    volumes:
      - ../hd1-movies:/var/www/html
    working_dir: /var/www/html
    command: bash -c "ENV=production grunt prod"
