version: "3"
services:
  main:
    image: hub.fimplus.io/repo/hd1-movies:v1.1
    networks:
      - fimplus
    deploy:
      mode: global
      placement:
        constraints: [node.labels.env == production]
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.servicePath=/
        - com.df.serviceDomain=movies.fimplus.vn
        - com.df.port=8080
        - com.df.httpsOnly=true

    networks:
      - fimplus

networks:
  fimplus:
    external: true
